# Generated by Django 3.2.4 on 2021-06-05 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMptt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STD', 'base employee'), ('TECH', 'technician'), ('MGR', 'manager'), ('SRMGR', 'senior manager'), ('PRES', 'president')], max_length=25, verbose_name='Должность')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('work_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало работы')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Заработная плата')),
                ('paid_out', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Выплаченная зарплата')),
                ('lvl', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='workers.employeemptt', verbose_name='Начальник')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
