# Generated by Django 3.2.4 on 2021-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_employeemptt_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemptt',
            name='paid_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Выплаченная зарплата'),
        ),
    ]
